/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/intent/': RouteRecordInfo<'/intent/', '/intent', Record<never, never>, Record<never, never>>,
    '/none/': RouteRecordInfo<'/none/', '/none', Record<never, never>, Record<never, never>>,
    '/render/': RouteRecordInfo<'/render/', '/render', Record<never, never>, Record<never, never>>,
    '/viewport/': RouteRecordInfo<'/viewport/', '/viewport', Record<never, never>, Record<never, never>>,
  }
}
